### ISSUE TITLE
Facebook 分享圖是上一期的

### ISSUE THREAD

**Issue by aelcenganda** [g0v/grantdash#39]
FB 分享的圖是上一期的，應該要換成這一期的。等一下子龍的圖，或是把現在的 svg 圖轉成jpg

**Comment by aelcenganda** [comment]
已 push，等 deploy

**Comment by zbryikt** [comment]
thumbnail.jpg seems not been updated, update with the new design and pushed.
done in ec86fa1713548098a3d2
