### ISSUE TITLE
最新消息內的文章超連結為白色看不見

### ISSUE THREAD

**Issue by aelcenganda** [g0v/grantdash#55]
最新消息內的文章超連結為白色看不見，因為底色為白色。
![2017-07-06 12 25 12](https://user-images.githubusercontent.com/9480974/27895591-52fac7fe-6246-11e7-9dcf-4b602e7c8bc6.png)

**Comment by aelcenganda** [comment]
還有邊界可以縮小一點嗎？就是 margin 多一點。

**Comment by zbryikt** [comment]
fixed 6a06691d0570dc7
所以 margin 是要變小還是要變多？我先 close 這張, margin 可以另外開一張..
