### ISSUE TITLE
執行團隊修改

### ISSUE THREAD

**Issue by besscsl** [g0v/grantdash#63]
圖片：https://drive.google.com/file/d/10W49eFx3MfHOcWDtG2MroIXoGwD_DzNr/view?usp=sharing

評選召集：王向榮 (ronnywang)
李慕約公司共同創辦人，g0v 社群長期參與者，發起與參與過新聞小幫手、求職小幫手、台灣公司資料、開放政治獻金等專案，希望更透明的政府可以讓大家有更自由幸福的生活。

圖片：https://drive.google.com/file/d/1cvWggd4eOtawgtmwGzUZfDK-MTZGyW2Q/view?usp=sharing

專案經理：李佳珊 (Bess)
曾在非營利組織推廣藝術進駐多年，對資訊平台、地圖協作和數位公民參與有興趣，期待可以從 g0v 新手變成填坑好手。

**Comment by zbryikt** [comment]
update in 2018 , 5fb44d051c4857ba3228435c9be2b6374f6faea9
