### ISSUE TITLE
/2018 的網址要能導回首頁

### ISSUE THREAD

**Issue by ronnywang** [g0v/grantdash#65]
目前這網址是專門放捷運上的以便了解來自捷運的瀏覽量

需要導回首頁，並且希望能記錄 page view

**Comment by zbryikt** [comment]
done. add a route to redirect /2018 to /
e474c80d8767c

**Comment by ronnywang** [comment]
不過好像這邊沒有做到記錄 page view ?

**Comment by zbryikt** [comment]
這個有跟 clkao 討論, 說是看 referrer 就好了
