### ISSUE TITLE
首頁大圖變形

### ISSUE THREAD

**Issue by ttcat** [g0v/grantdash#73]
CSS 修正

#landing {
    width: 100%;
    min-height: 638px;
    margin-top: 50px;
}

**Comment by ttcat** [comment]
但手機版看，margin 要改：
margin-top: -30px;

主要是大圖的 background 沒有考慮到 top nav

**Comment by zbryikt** [comment]
改用三層圖層 ( 重複灰色文字 / 主視覺 / 文字 ) + Media Query 重新調整, 並固定主視覺圖寬
fixed
