### ISSUE TITLE
編輯提案會產生新網址，導致資訊不連貫

### ISSUE THREAD

**Issue by kiang** [g0v/grantdash#76]
原本提案
https://grants.g0v.tw/projects/5a4926a98b4d8d001efe2e6b

編輯後變成
https://grants.g0v.tw/projects/5a5f388fa86841001b8167c7

但上傳的圖片、訂閱的人等資訊則是停留在舊有提案網址中

**Comment by kiang** [comment]
看起來是我按到新增提案

**Comment by ronnywang** [comment]
嗯，因為這期有新增加草稿的功能，只要編輯過程隨時會儲存草稿，在新增提案時會自動載入，避免電腦當機打白工。但是在新增完提案後沒有做清空草稿的動作，造成之後再點新增提案時會誤以為進到編輯畫面而新增了一筆。

在 694bbcb147c956ee492dbce53052330d90a3390b commit 解決這個問題了，新增提案後就會把草稿刪掉
另外也已經把已經送出提案的人在 mongodb 的草稿清除掉了
這邊也記錄一下在 mongo 下的指令

```
leader_titles = {}
leaders = []
db.projects.find({domain:'2018a'}).toArray().map(function(p){ leaders.push(p.leader + ''); leader_titles[p.leader + ''] = p.title; })
db.drafts.find({id:{"$in":leaders}}).map(function(d) { data=JSON.parse(d.draft); if(data.title==leader_titles[d.id]) { return db.drafts.remove({id:d.id}); } })
```
