### ISSUE TITLE
Add new partner @ partners.jade

### ISSUE THREAD

**Issue by besscsl** [g0v/grantdash#79]
logo - https://drive.google.com/open?id=1fXQQeDTiPeUa8dSyLm8TxB2nYwLF6Xyk
link - http://www.cht.com.tw/
oneword - 扮演數位經濟發動機，創新產業領航員。
detail - 

中華電信公司是國內最大的綜合電信業者，近年來積極擘畫由電信服務業（CT）轉型為最值得信賴的資通訊（ICT）服務公司，主要業務涵蓋固網通信、行動通信，及數據通信三大領域，提供語音服務、專線電路、網際網路、寬頻上網、智慧型網路、虛擬網路、電子商務、企業整合資通訊服務以及各類加值服務，為用戶創造優質的通訊環境與精彩便利的數位生活，也是國際間電信業者重要的合作夥伴。近年，中華電信亦積極投入「企業社會責任」各項作為，屢獲國內外專業機構的肯定。民國 94 年 8 月 12 日政府持有本公司股權降至 50％ 以下，本公司經營體制由國營事業轉為民營企業。

**Comment by zbryikt** [comment]
added 581c908111ff12089
