### ISSUE TITLE
Add new partner info

### ISSUE THREAD

**Issue by besscsl** [g0v/grantdash#80]
**Banner**
https://drive.google.com/drive/folders/1Co_8dWAD0uMs6fwhTeCsPGBfjQ5Glqb_?usp=sharing
Please use >>> 圖7_悠遊卡CI_橫式標準.ai

**Link**
http://www.easycard.com.tw/

**Oneword**
缺

**Text**
悠遊卡公司正式成立於 2000 年 3 月， 初期是以非接觸式 IC 智慧卡整合大台北地區公車、捷運及北市公有路外停車場，為電子化交通票證系統揭開新的里程碑，目前悠遊卡使用範圍則已更為擴展，從交通運輸如渡輪、纜車、高鐵、台鐵、國道客運、計程車、停車場等，再拓展至小額消費如便利超商、超市、餐廳、飲料，甚至連行政規費、風景區門票等，都可以用悠遊卡支付，提供民眾在食、衣、住、行各方面便利的支付工具，創造更美好的生活。

**Comment by zbryikt** [comment]
added. 
09503120639ebee684487fa87928cbf57fcb8df0
6f45a81ddf80b436cde4c4659f790fd62a7f58c6
