### ISSUE TITLE
grantdash/views/special-issue.jade

### ISSUE THREAD

**Issue by besscsl** [g0v/grantdash#81]
https://github.com/g0v/grantdash/blob/master/views/special-issue.jade

其實我改了兩個連結，另外一個是不是因為不正確所以沒出現？再麻煩了...謝謝！

>       //- 待 UDN 提供
      - var links = [["聯合報系願景工程官網","https://vision.udn.com/"]];
      - var links = [["聯合報系願景工程粉絲團","https://www.facebook.com/udn.vision.project/"]];
      if links.length
        h3 相關連結
        ul
          each item in links
            li: a(href=item[1])= item[0]

**Comment by zbryikt** [comment]
b1141a6530bafa42362796a56d8ef5188084e0f8 fixed
