### ISSUE TITLE
Add new partner

### ISSUE THREAD

**Issue by besscsl** [g0v/grantdash#82]
**AppWorks**

LOGO
https://drive.google.com/file/d/1AJIMS3GopL21zcez9auUP7U33248_Ycm/view?usp=sharing

LINK
https://appworks.tw/

ONEWORD
我們期待未來會有更多具有商業發展潛力與社會影響力的專案在 g0v 社群中誕生。

INTRO
AppWorks 是亞洲最大的創業加速器，自 2010 年成立以來，協助網路創業者結合線上與實體的活動，以自由開放、跨界社群、多邊交流精神，致力提升台灣的數位經濟實力，並提出政策建言，與政府、學界、產業交流，打造台灣最大的網路創業社群。此種精神與 g0v 的「公民參與社會」精神不謀而合，因此我們很樂意贊助此次公民科技創新獎，並期待未來會有更多具有商業發展潛力與社會影響力的專案在 g0v 社群中誕生，一同讓民間的創新能量發揮更大的影響力。

**Comment by zbryikt** [comment]
added. 4b7a7b4f859cc81c188c0
